import type { ProblemDetail } from "../types/problem";

export const PROBLEMS: ProblemDetail[] = [
  {
    id: "PK-2026-1043",
    referenceId: "#PK-2026-1043",
    title: "Harmu River Storm Conduit Severe Siltation & Monsoon Overflow",
    category: "Infrastructure",
    status: "Under Analysis",
    severity: "High",
    location: {
      area: "Harmu Colony Bypass",
      city: "Ranchi",
      state: "Jharkhand",
      distanceKm: 1.2,
    },
    submittedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80",
    upvotes: 68,
    commentsCount: 19,
    description: "Solid waste entrapment and sediment choke in 4.2 km main storm culverts causing road inundation and backflow during monsoon.",
    tags: ["Civic Infrastructure", "Urban Stormwater", "IoT Telemetry"],
    photos: [],
  },
  {
    id: "PK-2026-1044",
    referenceId: "#PK-2026-1044",
    title: "45 Blown 25kVA/63kVA Distribution Transformers in Rural Feeder",
    category: "Infrastructure",
    status: "Matching Teams",
    severity: "High",
    location: {
      area: "Jama & Jarmundi Blocks",
      city: "Dumka",
      state: "Jharkhand",
      distanceKm: 4.8,
    },
    submittedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&auto=format&fit=crop&q=80",
    upvotes: 84,
    commentsCount: 31,
    description: "Repeated surge burnouts in 25kVA pole-mounted transformers causing continuous power outages across 12 Gram Panchayats.",
    tags: ["Energy & Electrification", "Grid Protection", "Surge Arresters"],
    photos: [],
  },
  {
    id: "PK-2026-1045",
    referenceId: "#PK-2026-1045",
    title: "Excess Fluoride (>3.5 mg/L) Contamination in 28 Handpumps",
    category: "Healthcare",
    status: "In Progress",
    severity: "High",
    location: {
      area: "Patan & Chhatarpur Blocks",
      city: "Palamu",
      state: "Jharkhand",
      distanceKm: 6.1,
    },
    submittedAt: new Date(Date.now() - 9 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1546554137-f86b9593a222?w=600&auto=format&fit=crop&q=80",
    upvotes: 92,
    commentsCount: 27,
    description: "Geogenic fluoride poisoning in drinking water aquifers leading to dental and skeletal fluorosis among school children.",
    tags: ["Public Health", "Water Potability", "Activated Alumina"],
    photos: [],
  },
  {
    id: "PK-2026-1046",
    referenceId: "#PK-2026-1046",
    title: "PHC Vaccine Cold-Chain Thermal Excursions during Grid Outages",
    category: "Healthcare",
    status: "Solution Planned",
    severity: "Medium",
    location: {
      area: "Kolebira Primary Health Center",
      city: "Simdega",
      state: "Jharkhand",
      distanceKm: 3.4,
    },
    submittedAt: new Date(Date.now() - 14 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80",
    upvotes: 43,
    commentsCount: 12,
    description: "Frequent 8-14 hour grid cuts causing temperature rise in Ice-Lined Refrigerators, risking pentavalent and polio vaccine potency.",
    tags: ["Public Health", "Solar Cold Storage", "PCM Thermal"],
    photos: [],
  },
  {
    id: "PK-2026-1047",
    referenceId: "#PK-2026-1047",
    title: "Subsurface Coal Seam Fire Gas Fissures & Thermal Subsidence",
    category: "Environment",
    status: "Under Analysis",
    severity: "High",
    location: {
      area: "Jharia Sector 4 Settlement",
      city: "Dhanbad",
      state: "Jharkhand",
      distanceKm: 2.1,
    },
    submittedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    upvotes: 110,
    commentsCount: 45,
    description: "Surface fissure emission of Carbon Monoxide (CO) and ground surface temperatures reaching 78°C near human dwellings.",
    tags: ["Mining Safety", "Thermal Telemetry", "Geotechnical"],
    photos: [],
  },
  {
    id: "PK-2026-1048",
    referenceId: "#PK-2026-1048",
    title: "Off-Grid Digital Classroom Smartboard Battery & Solar Deficits",
    category: "Education",
    status: "In Discussion",
    severity: "Medium",
    location: {
      area: "Manoharpur Tribal Middle School",
      city: "West Singhbhum",
      state: "Jharkhand",
      distanceKm: 7.5,
    },
    submittedAt: new Date(Date.now() - 22 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80",
    upvotes: 39,
    commentsCount: 8,
    description: "Over 22 tribal schools unable to run digital teaching displays and audio sets due to irregular power supply and lack of solar backup.",
    tags: ["Education", "Solar Microgrid", "Offline Courseware"],
    photos: [],
  },
  {
    id: "PK-2026-1049",
    referenceId: "#PK-2026-1049",
    title: "Post-Harvest Perishability of Mahua & Lac Forest Produce",
    category: "Agriculture",
    status: "Matching Teams",
    severity: "Medium",
    location: {
      area: "Chitarpur Gram Panchayat",
      city: "Ramgarh",
      state: "Jharkhand",
      distanceKm: 4.1,
    },
    submittedAt: new Date(Date.now() - 28 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=600&auto=format&fit=crop&q=80",
    upvotes: 56,
    commentsCount: 14,
    description: "Heavy post-harvest wastage of NTFP (Non-Timber Forest Produce) due to lack of solar micro-dehydrators and temperature-controlled storage.",
    tags: ["Agriculture", "Solar Dehydrators", "Cold Storage"],
    photos: [],
  },
  {
    id: "PK-2026-1050",
    referenceId: "#PK-2026-1050",
    title: "Unsafe Damaged Culvert on Bokaro Industrial Haulage Road",
    category: "Infrastructure",
    status: "In Progress",
    severity: "High",
    location: {
      area: "Bokaro Steel City Sector 9",
      city: "Bokaro",
      state: "Jharkhand",
      distanceKm: 1.8,
    },
    submittedAt: new Date(Date.now() - 32 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    upvotes: 72,
    commentsCount: 22,
    description: "Structural fracture in concrete haulage culvert under heavy slag transport trucks threatening total transport collapse.",
    tags: ["Transport", "Bridge Structural Health", "Civil Infra"],
    photos: [],
  },
  {
    id: "PK-2026-1051",
    referenceId: "#PK-2026-1051",
    title: "Industrial Effluent Discharge in Subarnarekha River Basin",
    category: "Environment",
    status: "Under Analysis",
    severity: "High",
    location: {
      area: "Adityapur Industrial Area",
      city: "Seraikela-Kharsawan",
      state: "Jharkhand",
      distanceKm: 3.9,
    },
    submittedAt: new Date(Date.now() - 40 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1621451537084-482c73073a0f?w=600&auto=format&fit=crop&q=80",
    upvotes: 89,
    commentsCount: 34,
    description: "Unmonitored acidic and heavy-metal industrial effluent discharge into river tributaries affecting downstream agricultural irrigation.",
    tags: ["Effluent Monitoring", "Water Quality", "IoT Sensors"],
    photos: [],
  },
  {
    id: "PK-2026-1052",
    referenceId: "#PK-2026-1052",
    title: "Solar Irrigation Microgrid Pump Inverter Failures in High Heat",
    category: "Agriculture",
    status: "Solution Planned",
    severity: "Low",
    location: {
      area: "Kanke Block Agricultural Cluster",
      city: "Ranchi",
      state: "Jharkhand",
      distanceKm: 5.2,
    },
    submittedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop&q=80",
    upvotes: 31,
    commentsCount: 7,
    description: "Thermal tripping of MPPT variable frequency drives during peak afternoon solar radiation affecting paddy irrigation schedules.",
    tags: ["Solar Pumping", "Inverter Cooling", "Agriculture"],
    photos: [],
  },
  {
    id: "PK-2026-1053",
    referenceId: "#PK-2026-1053",
    title: "Maternal Health Telemedicine Ultrasound Connectivity Dropouts",
    category: "Healthcare",
    status: "In Discussion",
    severity: "Medium",
    location: {
      area: "Madhupur Subdivisional Hospital",
      city: "Deoghar",
      state: "Jharkhand",
      distanceKm: 8.3,
    },
    submittedAt: new Date(Date.now() - 54 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&auto=format&fit=crop&q=80",
    upvotes: 47,
    commentsCount: 11,
    description: "Cellular packet drops hindering real-time tele-sonography transmission between rural health centers and AIIMS Deoghar specialists.",
    tags: ["Telemedicine", "Rural Health", "Satellite Mesh"],
    photos: [],
  },
  {
    id: "PK-2026-1054",
    referenceId: "#PK-2026-1054",
    title: "Mica Mining Quarry Hazardous Abandoned Pits near Villages",
    category: "Others",
    status: "Under Analysis",
    severity: "High",
    location: {
      area: "Tisri & Gawan Blocks",
      city: "Giridih",
      state: "Jharkhand",
      distanceKm: 9.7,
    },
    submittedAt: new Date(Date.now() - 60 * 3600000).toISOString(),
    thumbnailUrl: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=600&auto=format&fit=crop&q=80",
    upvotes: 63,
    commentsCount: 18,
    description: "Unfenced open quarry craters accumulating rainwater and causing fatal drowning hazards and soil erosion during monsoons.",
    tags: ["Mine Safety", "Fencing & Telemetry", "Civic Protection"],
    photos: [],
  },
];

export function getProblemById(id: string) {
  return PROBLEMS.find((problem) => problem.id === id || problem.referenceId === id);
}